### ISSUE TITLE
[PE-D][Tester B] Nearest MRT Station Field Accepting Unintended String Values

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-2/tp#130]
I would like to report a bug related to the Nearest MRT Station field in your application. Currently, the field allows users to input a wide range of string values, rather than restricting it to the intended MRT station.

Steps to reproduce: 
1. Run Tutorium.jar
2. Add a new person with this command: add n/John Doe p/12345678 e/johnd@example.com a/John street, block 123, #01-01 g/M l/2 m/invalid s/Chemistry s/Physics
3. Observe that the field accepts any string input without validation.

Expected Behavior:
The Nearest MRT Station field should only allow users to select from a predefined list of MRT stations, ensuring data accuracy and consistency.

Actual Behavior:
The field currently accepts arbitrary string values, leading to potential inaccuracies and user confusion.

Suggestion:
It might be a bit tedious, but a good approach is to create a switch to validate all cases for all MRT stations across Singapore.

![image.png](https://raw.githubusercontent.com/Leb14/ped/main/files/50880c24-e2ca-41ab-8f80-bc38e3192dbc.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Leb14/ped#1

**Comment by laurenlim2112** [comment]
Possible fix: Specify in the UG that input validation for nearest MRT station is a planned future improvement.
