### ISSUE TITLE
[PE-D][Tester D] Error message not clear 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-2/tp#153]
![image.png](https://raw.githubusercontent.com/saraozn/ped/main/files/4804f39c-4889-4908-8379-0a87d88f7b22.png)

This error message was slightly confusing, could be improved to tell me that a subject is required for the date to be edited

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: saraozn/ped#6

**Comment by laurenlim2112** [comment]
Categorised functionality bug as the error message is simply incorrect (at least one field was indeed provided for editing).
