### ISSUE TITLE
[PE-D][Tester C] Allowed values for address unclear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W13-2/tp#161]
Not clear what inputs are allowed for address; someone stays at at electronic-house, which I want to shorten to `e/house` but it wasn't allowed :(

Input:

`add n/John Doe p/12345678 e/johnd@example.com a/ e/house g/M l/2 m/KR mrt s/Chemistry s/Physics`

Result:

![image.png](https://raw.githubusercontent.com/jedkohjk/ped/main/files/b2c669d6-09b9-4299-9283-87961b15abdd.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jedkohjk/ped#16

**Comment by laurenlim2112** [comment]
Update UG to show that invalid values for fields
